# Generated by Django 3.1.3 on 2020-12-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201220_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
