# Generated by Django 3.1.3 on 2021-01-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='on_watchlist',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
