# Generated by Django 3.1.3 on 2021-01-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210101_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='on_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
